language: scala
jdk: oraclejdk8
scala: 2.12.4

git:
  depth: false

stages:
  - name: build

jobs:
  include:
    - stage: build
      script: sbt package

branches:
  only: master

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
